### ISSUE TITLE
与ioncube_loader_lin_7.2.so 和opencv3.3不兼容

### ISSUE THREAD

**Issue by icyxp** [yunnian/php-nsq#10]
`*** Error in `php': free(): invalid pointer: 0x00007f3a14e5b7a8 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7c619)[0x7f3a22d45619]
php(zend_hash_destroy+0xa5)[0x8619f5]
php(php_request_shutdown+0x30e)[0x7eedae]
php[0x901ee7]
php[0x43de98]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f3a22ceac05]
php[0x43dfaa]
======= Memory map: ========
00400000-010e7000 r-xp 00000000 fd:04 266118                             /usr/local/php/bin/php
012e6000-013a8000 r--p 00ce6000 fd:04 266118                             /usr/local/php/bin/php
013a8000-013d4000 rw-p 00da8000 fd:04 266118                             /usr/local/php/bin/php
013d4000-013fa000 rw-p 00000000 00:00 0 
01c82000-01fe5000 rw-p 00000000 00:00 0                                  [heap]
7f3a10000000-7f3a10021000 rw-p 00000000 00:00 0 
7f3a10021000-7f3a14000000 ---p 00000000 00:00 0 
7f3a14e00000-7f3a15200000 rw-p 00000000 00:00 0 
7f3a152bd000-7f3a154be000 rw-s 00000000 00:04 103609                     /dev/zero (deleted)
7f3a154be000-7f3a154d5000 r-xp 00000000 fd:04 266661                     /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/molten.so
7f3a154d5000-7f3a156d4000 ---p 00017000 fd:04 266661                     /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/molten.so
7f3a156d4000-7f3a156d5000 r--p 00016000 fd:04 266661                     /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/molten.so
7f3a156d5000-7f3a156d6000 rw-p 00017000 fd:04 266661                     /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/molten.so
7f3a156d6000-7f3a15729000 r-xp 00000000 fd:04 139843                     /usr/lib64/libevent-2.1.so.6.0.2
7f3a15729000-7f3a15928000 ---p 00053000 fd:04 139843                     /usr/lib64/libevent-2.1.so.6.0.2
7f3a15928000-7f3a15929000 r--p 00052000 fd:04 139843                     /usr/lib64/libevent-2.1.so.6.0.2
7f3a15929000-7f3a1592a000 rw-p 00053000 fd:04 139843                     /usr/lib64/libevent-2.1.so.6.0.2
7f3a1592a000-7f3a1592b000 rw-p 00000000 00:00 0 
7f3a1592b000-7f3a15932000 r-xp 00000000 fd:04 266662                     /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/nsq.so
7f3a15932000-7f3a15b32000 ---p 00007000 fd:04 266662                     /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/nsq.so
7f3a15b32000-7f3a15b33000 r--p 00007000 fd:04 266662                     /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/nsq.so
7f3a15b33000-7f3a15b34000 rw-p 00008000 fd:04 266662                     /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/nsq.so
7f3a15b34000-7f3a15be4000 r-xp 00000000 fd:04 266666                     /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/swoole.so
7f3a15be4000-7f3a15de4000 ---p 000b0000 fd:04 266666                     /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/swoole.so
7f3a15de4000-7f3a15dee000 r--p 000b0000 fd:04 266666                     /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/swoole.so
7f3a15dee000-7f3a15e00000 rw-p 000ba000 fd:04 266666                     /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/swoole.so
7f3a15e00000-7f3a15e7f000 rw-p 00000000 00:00 0 
7f3a15e7f000-7f3a160d2000 r-xp 00000000 fd:04 139874                     /usr/lib64/liblept.so.5.0.1
7f3a160d2000-7f3a162d2000 ---p 00253000 fd:04 139874                     /usr/lib64/liblept.so.5.0.1
7f3a162d2000-7f3a162d3000 r--p 00253000 fd:04 139874                     /usr/lib64/liblept.so.5.0.1
7f3a162d3000-7f3a162dc000 rw-p 00254000 fd:04 139874                     /usr/lib64/liblept.so.5.0.1
7f3a162dc000-7f3a16302000 r-xp 00000000 fd:04 139922                     /usr/lib64/libopencv_videoio.so.3.3.0
7f3a16302000-7f3a16502000 ---p 00026000 fd:04 139922                     /usr/lib64/libopencv_videoio.so.3.3.0
7f3a16502000-7f3a16503000 r--p 00026000 fd:04 139922                     /usr/lib64/libopencv_videoio.so.3.3.0
7f3a16503000-7f3a16504000 rw-p 00027000 fd:04 139922                     /usr/lib64/libopencv_videoio.so.3.3.0
7f3a16504000-7f3a16507000 rw-p 00000000 00:00 0 
7f3a16507000-7f3a16527000 r-xp 00000000 fd:04 139935                     /usr/lib64/libzbar.so.0.2.0
7f3a16527000-7f3a16727000 ---p 00020000 fd:04 139935                     /usr/lib64/libzbar.so.0.2.0
7f3a16727000-7f3a16728000 r--p 00020000 fd:04 139935                     /usr/lib64/libzbar.so.0.2.0
7f3a16728000-7f3a16729000 rw-p 00021000 fd:04 139935                     /usr/lib64/libzbar.so.0.2.0
7f3a16729000-7f3a16ebc000 r-xp 00000000 fd:04 139869                     /usr/lib64/libgs.so.9.22
7f3a16ebc000-7f3a170bc000 ---p 00793000 fd:04 139869                     /usr/lib64/libgs.so.9.22
7f3a170bc000-7f3a1745d000 r--p 00793000 fd:04 139869                     /usr/lib64/libgs.so.9.22
7f3a1745d000-7f3a18014000 rw-p 00b34000 fd:04 139869                     /usr/lib64/libgs.so.9.22
7f3a18014000-7f3a18015000 rw-p 00000000 00:00 0 
7f3a18015000-7f3a1831c000 r-xp 00000000 fd:04 139930                     /usr/lib64/libtesseract.so.3.0.5
7f3a1831c000-7f3a1851b000 ---p 00307000 fd:04 139930                     /usr/lib64/libtesseract.so.3.0.5
7f3a1851b000-7f3a18521000 r--p 00306000 fd:04 139930                     /usr/lib64/libtesseract.so.3.0.5
7f3a18521000-7f3a18529000 rw-p 0030c000 fd:04 139930                     /usr/lib64/libtesseract.so.3.0.5
7f3a18529000-7f3a187bf000 rw-p 00000000 00:00 0 
7f3a187bf000-7f3a18c1a000 r-xp 00000000 fd:04 139907                     /usr/lib64/libopencv_photo.so.3.3.0
7f3a18c1a000-7f3a18e1a000 ---p 0045b000 fd:04 139907                     /usr/lib64/libopencv_photo.so.3.3.0
7f3a18e1a000-7f3a18e1e000 r--p 0045b000 fd:04 139907                     /usr/lib64/libopencv_photo.so.3.3.0
7f3a18e1e000-7f3a18e28000 rw-p 0045f000 fd:04 139907                     /usr/lib64/libopencv_photo.so.3.3.0
7f3a18e28000-7f3a1945f000 r-xp 00000000 fd:04 139895                     /usr/lib64/libopencv_imgcodecs.so.3.3.0
7f3a1945f000-7f3a1965e000 ---p 00637000 fd:04 139895                     /usr/lib64/libopencv_imgcodecs.so.3.3.0
7f3a1965e000-7f3a19667000 r--p 00636000 fd:04 139895                     /usr/lib64/libopencv_imgcodecs.so.3.3.0
7f3a19667000-7f3a19676000 rw-p 0063f000 fd:04 139895                     /usr/lib64/libopencv_imgcodecs.so.3.3.0
7f3a19676000-7f3a19680000 rw-p 00000000 00:00 0 
7f3a19680000-7f3a1cf05000 r-xp 00000000 fd:04 139898                     /usr/lib64/libopencv_imgproc.so.3.3.0
7f3a1cf05000-7f3a1d104000 ---p 03885000 fd:04 139898                     /usr/lib64/libopencv_imgproc.so.3.3.0
7f3a1d104000-7f3a1d124000 r--p 03884000 fd:04 139898                     /usr/lib64/libopencv_imgproc.so.3.3.0
7f3a1d124000-7f3a1d152000 rw-p 038a4000 fd:04 139898                     /usr/lib64/libopencv_imgproc.so.3.3.0
7f3a1d152000-7f3a1d3c6000 rw-p 00000000 00:00 0 
7f3a1d3c6000-7f3a1d3d0000 r-xp 00000000 fd:04 139892                     /usr/lib64/libopencv_highgui.so.3.3.0
7f3a1d3d0000-7f3a1d5cf000 ---p 0000a000 fd:04 139892                     /usr/lib64/libopencv_highgui.so.3.3.0
7f3a1d5cf000-7f3a1d5d0000 r--p 00009000 fd:04 139892                     /usr/lib64/libopencv_highgui.so.3.3.0
7f3a1d5d0000-7f3a1d5d1000 rw-p 0000a000 fd:04 139892                     /usr/lib64/libopencv_highgui.so.3.3.0
7f3a1d5d1000-7f3a1e745000 r-xp 00000000 fd:04 139880                     /usr/lib64/libopencv_core.so.3.3.0
7f3a1e745000-7f3a1e945000 ---p 01174000 fd:04 139880                     /usr/lib64/libopencv_core.so.3.3.0
7f3a1e945000-7f3a1e953000 r--p 01174000 fd:04 139880                     /usr/lib64/libopencv_core.so.3.3.0
7f3a1e953000-7f3a1e983000 rw-p 01182000 fd:04 139880                     /usr/lib64/libopencv_core.so.3.3.0
7f3a1e983000-7f3a1e988000 rw-p 00000000 00:00 0 
7f3a1e988000-7f3a1e99d000 r-xp 00000000 fd:04 133321                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f3a1e99d000-7f3a1eb9c000 ---p 00015000 fd:04 133321                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f3a1eb9c000-7f3a1eb9d000 r--p 00014000 fd:04 133321                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f3a1eb9d000-7f3a1eb9e000 rw-p 00015000 fd:04 133321                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f3a1eb9e000-7f3a1ec87000 r-xp 00000000 fd:04 133504                     /usr/lib64/libstdc++.so.6.0.19
7f3a1ec87000-7f3a1ee87000 ---p 000e9000 fd:04 133504                     /usr/lib64/libstdc++.so.6.0.19
7f3a1ee87000-7f3a1ee8f000 r--p 000e9000 fd:04 133504                     /usr/lib64/libstdc++.so.6.0.19
7f3a1ee8f000-7f3a1ee91000 rw-p 000f1000 fd:04 133504                     /usr/lib64/libstdc++.so.6.0.19
7f3a1ee91000-7f3a1eea6000 rw-p 00000000 00:00 0 
7f3a1eea6000-7f3a1efa6000 r-xp 00000000 fd:04 140307                     /usr/lib64/libocr.so.1.0.1
7f3a1efa6000-7f3a1f1a5000 ---p 00100000 fd:04 140307                     /usr/lib64/libocr.so.1.0.1
7f3a1f1a5000-7f3a1f1a7000 r--p 000ff000 fd:04 140307                     /usr/lib64/libocr.so.1.0.1
7f3a1f1a7000-7f3a1f1ae000 rw-p 00101000 fd:04 140307                     /usr/lib64/libocr.so.1.0.1
7f3a1f1ae000-7f3a1f1b0000 r-xp 00000000 fd:04 266663                     /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/ocr.so
7f3a1f1b0000-7f3a1f3af000 ---p 00002000 fd:04 266663                     /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/ocr.so
7f3a1f3af000-7f3a1f3b0000 r--p 00001000 fd:04 266663                     /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/ocr.so
7f3a1f3b0000-7f3a1f3b1000 rw-p 00002000 fd:04 266663                     /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/ocr.so
7f3a1f3b1000-7f3a1f4ed000 r-xp 00000000 fd:04 266660                     /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/ioncube_loader_lin_7.2.so
7f3a1f4ed000-7f3a1f5ed000 ---p 0013c000 fd:04 266660                     /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/ioncube_loader_lin_7.2.so
7f3a1f5ed000-7f3a1f5fd000 rw-p 0013c000 fd:04 266660                     /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/ioncube_loader_lin_7.2.soAborted (core dumped)`

**Comment by yunnian** [comment]
加下微信 方便沟通， 18610998596，尽快的解决你遇到的问题

**Comment by yunnian** [comment]
没测出什么问题， 看起来是ioncube_loader_lin_7.2.so 发生了coredump，可以加我微信18610998596 方便沟通，从而尽快解决您的问题

**Comment by yunnian** [comment]
使用最新master 代码试下

**Comment by icyxp** [comment]
已加微信，麻烦通过下，谢谢！
