### ISSUE TITLE
Bad links on PECL page

### ISSUE THREAD

**Issue by remicollet** [yunnian/php-nsq#23]
On https://pecl.php.net/package/nsq

- Package Bugs => https://bugs.php.net/search.php?cmd=display&status=Open&package_name[]=nsq
- Report new bug => https://bugs.php.net/report.php?package=nsq
 

Please fix them.

**Comment by yunnian** [comment]
I did not find the place or button  can update it 
Could you tell me how update it?

**Comment by remicollet** [comment]
Once, logged, on the package page, you have a "pen" link (on the left of `[Edit maintainers]`)

**Comment by yunnian** [comment]
Thank you  ,I have repaired it,
You are really nice man!

**Comment by remicollet** [comment]
ty
