### ISSUE TITLE
Replying to heartbeats when a job is long-running

### ISSUE THREAD

**Issue by leonth** [yunnian/php-nsq#3]
According to https://github.com/davegardnerisme/nsqphp:

> nsq is not designed as a work queue (for long running tasks) out of the box. [...] Additionally, PHP is a blocking language, and although we are using a non-blocking IO event loop, any work you do to process a message will block the client from being able to reply to any heartbeats etc.

Does this client have the same issue? Can this client reply to heartbeats when a job is long-running?

**Comment by yunnian** [comment]
yes, the go client have the same problem, if the callback block 60 seconds. but It will retry connect.
In addition，you can improve the heartbeat time.

**Comment by leonth** [comment]
I see. Is there a way to manually handle heartbeats? E.g. when I am doing a bulk action of 1000 items, and 1 item needs 1 second processing time, I can call something like `handleHeartBeat()` after every item to avoid timeout.

**Comment by yunnian** [comment]
The heartbeat is the nsq sent to client ,client be recived and response ,so  ,haven't that function.

You can specify the --max-heartbeat-interval flag when starting nsqd to set a non-default limit.

**Comment by leonth** [comment]
I see that you are using libevent, so I checked the official nsq client for nodejs https://github.com/dudleycarr/nsqjs and they actually have this function (like the `handleHeartBeat()` I mentioned):

```
touch()
Tell nsqd that you want extra time to process the message. It extends the soft timeout by the normal timeout amount.
```

**Comment by yunnian** [comment]
Thank you for reminding me！
I see that, I will support it today.
When I finish, I'll remind you.

thank you again.

**Comment by yunnian** [comment]
Touch support has been completed 
You can use the new version

**Comment by leonth** [comment]
Wow thank you very much for your hard work! Will look into it
