### ISSUE TITLE
Compile warning

### ISSUE THREAD

**Issue by mia0x75** [yunnian/php-nsq#32]
/opt/downloads/php-nsq/nsq_lookupd.c:85:32: warning: ‘enum evhttp_request_error’ declared inside parameter list [enabled by default]
 void RequestErrorCallback(enum evhttp_request_error *error, void *arg) {
                                ^
/opt/downloads/php-nsq/nsq_lookupd.c:85:32: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]

**Comment by yunnian** [comment]
没事儿，这个不用理会
