### ISSUE TITLE
touch不支持多nsqd连接

### ISSUE THREAD

**Issue by jueljust** [yunnian/php-nsq#34]
场景复现条件
- subscribe 使用 nsqlookupd
- nsqlookupd 返回不止一个nsqd
- 单个msg执行过程超过nsqdtimeout时间
- 在msg执行过程中手动执行touch

期望
- 消费者进程能够保持对所有nsqd的连接

结果
- 消费者进程对当前msg以外的nsqd都因为超过timeout时间没有交互而断链

最好能自动对所有自动发nop保持连接
或者对这个行为可以配置

**Comment by yunnian** [comment]
timeout 连接断掉后 会自动重连的 ，超时断掉不是客户端能控制的，是server 主动断了你的连接，因为你心跳一直没响应

**Comment by yunnian** [comment]
timeout 连接断掉后 会自动重连的 ，超时断掉不是客户端能控制的，是server 主动断了你的连接，因为你心跳一直没响应
