### ISSUE TITLE
subscribe 方法回调函数内抛出异常而没有捕捉的时，消息会一直不停的再次接收

### ISSUE THREAD

**Issue by chechao** [yunnian/php-nsq#35]
subscribe 方法回调函数内抛出异常而没有捕捉的时，消息会一直不停的再次接收

`
$nsq->subscribe($nsq_lookupd, $config, function ($msg, $bev) use ($db, $redis) {
    var_dump($msg->payload);
    throw new Exception('E');
});
`

**Comment by yunnian** [comment]
这个是正常的 ，抛异常就认为你要重试这条消息
