### ISSUE TITLE
centos php7.2.9 make失败

### ISSUE THREAD

**Issue by chenny** [yunnian/php-nsq#40]
![image](https://user-images.githubusercontent.com/883329/45489363-a0780e00-b796-11e8-9c2e-672edf475f4c.png)
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
[root@hhweb php-nsq]# make && make install
/bin/sh /app/soft/php7_ext/php-nsq/libtool --mode=compile cc  -I. -I/app/soft/php7_ext/php-nsq -DPHP_ATOM_INC -I/app/soft/php7_ext/php-nsq/include -I/app/soft/php7_ext/php-nsq/main -I/app/soft/php7_ext/php-nsq -I/app/server/php7/include/php -I/app/server/php7/include/php/main -I/app/server/php7/include/php/TSRM -I/app/server/php7/include/php/Zend -I/app/server/php7/include/php/ext -I/app/server/php7/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /app/soft/php7_ext/php-nsq/nsq.c -o nsq.lo
mkdir .libs
 cc -I. -I/app/soft/php7_ext/php-nsq -DPHP_ATOM_INC -I/app/soft/php7_ext/php-nsq/include -I/app/soft/php7_ext/php-nsq/main -I/app/soft/php7_ext/php-nsq -I/app/server/php7/include/php -I/app/server/php7/include/php/main -I/app/server/php7/include/php/TSRM -I/app/server/php7/include/php/Zend -I/app/server/php7/include/php/ext -I/app/server/php7/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /app/soft/php7_ext/php-nsq/nsq.c  -fPIC -DPIC -o .libs/nsq.o
/bin/sh /app/soft/php7_ext/php-nsq/libtool --mode=compile cc  -I. -I/app/soft/php7_ext/php-nsq -DPHP_ATOM_INC -I/app/soft/php7_ext/php-nsq/include -I/app/soft/php7_ext/php-nsq/main -I/app/soft/php7_ext/php-nsq -I/app/server/php7/include/php -I/app/server/php7/include/php/main -I/app/server/php7/include/php/TSRM -I/app/server/php7/include/php/Zend -I/app/server/php7/include/php/ext -I/app/server/php7/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /app/soft/php7_ext/php-nsq/pub.c -o pub.lo
 cc -I. -I/app/soft/php7_ext/php-nsq -DPHP_ATOM_INC -I/app/soft/php7_ext/php-nsq/include -I/app/soft/php7_ext/php-nsq/main -I/app/soft/php7_ext/php-nsq -I/app/server/php7/include/php -I/app/server/php7/include/php/main -I/app/server/php7/include/php/TSRM -I/app/server/php7/include/php/Zend -I/app/server/php7/include/php/ext -I/app/server/php7/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /app/soft/php7_ext/php-nsq/pub.c  -fPIC -DPIC -o .libs/pub.o
/bin/sh /app/soft/php7_ext/php-nsq/libtool --mode=compile cc  -I. -I/app/soft/php7_ext/php-nsq -DPHP_ATOM_INC -I/app/soft/php7_ext/php-nsq/include -I/app/soft/php7_ext/php-nsq/main -I/app/soft/php7_ext/php-nsq -I/app/server/php7/include/php -I/app/server/php7/include/php/main -I/app/server/php7/include/php/TSRM -I/app/server/php7/include/php/Zend -I/app/server/php7/include/php/ext -I/app/server/php7/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /app/soft/php7_ext/php-nsq/nsq_lookupd.c -o nsq_lookupd.lo
 cc -I. -I/app/soft/php7_ext/php-nsq -DPHP_ATOM_INC -I/app/soft/php7_ext/php-nsq/include -I/app/soft/php7_ext/php-nsq/main -I/app/soft/php7_ext/php-nsq -I/app/server/php7/include/php -I/app/server/php7/include/php/main -I/app/server/php7/include/php/TSRM -I/app/server/php7/include/php/Zend -I/app/server/php7/include/php/ext -I/app/server/php7/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /app/soft/php7_ext/php-nsq/nsq_lookupd.c  -fPIC -DPIC -o .libs/nsq_lookupd.o
In file included from /app/soft/php7_ext/php-nsq/nsq_lookupd.c:32:0:
/usr/local/include/event.h:325:13: 错误：与‘event_base_get_method’类型冲突
 const char *event_base_get_method(struct event_base *);
             ^
In file included from /app/soft/php7_ext/php-nsq/nsq_lookupd.c:27:0:
/usr/include/event2/event.h:372:13: 附注：‘event_base_get_method’的上一个声明在此
 const char *event_base_get_method(const struct event_base *);
             ^
In file included from /app/soft/php7_ext/php-nsq/nsq_lookupd.c:32:0:
/usr/local/include/event.h:641:5: 错误：与‘event_pending’类型冲突
 int event_pending(struct event *ev, short event, struct timeval *tv);
     ^
In file included from /app/soft/php7_ext/php-nsq/nsq_lookupd.c:27:0:
/usr/include/event2/event.h:982:5: 附注：‘event_pending’的上一个声明在此
 int event_pending(const struct event *ev, short events, struct timeval *tv);
     ^
In file included from /app/soft/php7_ext/php-nsq/nsq_lookupd.c:32:0:
/usr/local/include/event.h:1035:6: 错误：嵌套的‘enum evbuffer_eol_style’重定义
 enum evbuffer_eol_style {
      ^
/usr/local/include/event.h:1035:6: 错误：‘enum evbuffer_eol_style’重声明
In file included from /app/soft/php7_ext/php-nsq/nsq_lookupd.c:28:0:
/usr/include/event2/buffer.h:362:6: 附注：原先在这里定义
 enum evbuffer_eol_style {
      ^
In file included from /app/soft/php7_ext/php-nsq/nsq_lookupd.c:32:0:
/usr/local/include/event.h:1037:2: 错误：枚举‘EVBUFFER_EOL_ANY’重声明
  EVBUFFER_EOL_ANY,
  ^
In file included from /app/soft/php7_ext/php-nsq/nsq_lookupd.c:28:0:
/usr/include/event2/buffer.h:372:2: 附注：‘EVBUFFER_EOL_ANY’的上一个定义在此
  EVBUFFER_EOL_ANY,
  ^
In file included from /app/soft/php7_ext/php-nsq/nsq_lookupd.c:32:0:
/usr/local/include/event.h:1040:2: 错误：枚举‘EVBUFFER_EOL_CRLF’重声明
  EVBUFFER_EOL_CRLF,
  ^
In file included from /app/soft/php7_ext/php-nsq/nsq_lookupd.c:28:0:
/usr/include/event2/buffer.h:375:2: 附注：‘EVBUFFER_EOL_CRLF’的上一个定义在此
  EVBUFFER_EOL_CRLF,
  ^
In file included from /app/soft/php7_ext/php-nsq/nsq_lookupd.c:32:0:
/usr/local/include/event.h:1042:2: 错误：枚举‘EVBUFFER_EOL_CRLF_STRICT’重声明
  EVBUFFER_EOL_CRLF_STRICT,
  ^
In file included from /app/soft/php7_ext/php-nsq/nsq_lookupd.c:28:0:
/usr/include/event2/buffer.h:377:2: 附注：‘EVBUFFER_EOL_CRLF_STRICT’的上一个定义在此
  EVBUFFER_EOL_CRLF_STRICT,
  ^
In file included from /app/soft/php7_ext/php-nsq/nsq_lookupd.c:32:0:
/usr/local/include/event.h:1044:9: 错误：枚举‘EVBUFFER_EOL_LF’重声明
         EVBUFFER_EOL_LF
         ^
In file included from /app/soft/php7_ext/php-nsq/nsq_lookupd.c:28:0:
/usr/include/event2/buffer.h:379:2: 附注：‘EVBUFFER_EOL_LF’的上一个定义在此
  EVBUFFER_EOL_LF
  ^
In file included from /app/soft/php7_ext/php-nsq/nsq_lookupd.c:32:0:
/usr/local/include/event.h:1110:6: 错误：与‘evbuffer_drain’类型冲突
 void evbuffer_drain(struct evbuffer *, size_t);
      ^
In file included from /app/soft/php7_ext/php-nsq/nsq_lookupd.c:28:0:
/usr/include/event2/buffer.h:505:5: 附注：‘evbuffer_drain’的上一个声明在此
 int evbuffer_drain(struct evbuffer *buf, size_t len);
     ^
/app/soft/php7_ext/php-nsq/nsq_lookupd.c:85:32: 警告：‘enum evhttp_request_error’在形参表内部声明 [默认启用]
 void RequestErrorCallback(enum evhttp_request_error *error, void *arg) {
                                ^
/app/soft/php7_ext/php-nsq/nsq_lookupd.c:85:32: 警告：它的作用域仅限于此定义或声明，这可能并不是您想要的 [默认启用]
make: *** [nsq_lookupd.lo] 错误 1

**Comment by yunnian** [comment]
检查下 是否有重复的 libevent 头文件，删掉旧的
