### ISSUE TITLE
启动1个订阅 出现了2个进程 

### ISSUE THREAD

**Issue by lingfan** [yunnian/php-nsq#41]
2个进程 内存就双倍了哦
![1](https://user-images.githubusercontent.com/455872/47058545-26ed9880-d1f8-11e8-84ba-be06887e9586.png)
![2](https://user-images.githubusercontent.com/455872/47058554-2ead3d00-d1f8-11e8-8ab0-b9b57b90eca1.png)
![3](https://user-images.githubusercontent.com/455872/47058559-310f9700-d1f8-11e8-8e94-475a693d931d.png)

php 7.1.21
centos7
php-nsq version => 3.1.0

**Comment by yunnian** [comment]
有一个主进程，其他是根据nsqd 数量分配的。  如果你config 数组里写的进程数是1，你有2个nsqd 就是一个主进程 两个子进程总共三个进程

**Comment by yunnian** [comment]
有一个是主进程，config 配置的是每个nsqd 的链接数，假设你有2nsqd ，config配置的链接数是1，那么就有2个子进程 +1个主进程，总共3个
