### ISSUE TITLE
mac php7.2.12 subscribe 直接child 42759 terminated, will reload

### ISSUE THREAD

**Issue by hppking** [yunnian/php-nsq#42]

**Comment by yunnian** [comment]
你代码贴下

**Comment by Sparkinzy** [comment]
mac 运行文档上的demo代码，结果如下：
child 29551 terminated, will reload

$config['channel'] = '';

publish消息的时候，没有这个channel数据，取值的时候有这个数据，是不是不恰当

**Comment by yunnian** [comment]
@Sparkinzy 恩，肯定要指定channel的
