### ISSUE TITLE
配置能否说明下作用，谢谢

### ISSUE THREAD

**Issue by icyxp** [yunnian/php-nsq#5]
$config = array(
    "topic" => "test",
    "channel" => "struggle",
    "rdy" => 10,
    "connect_num" => 1, 
    "retry_delay_time" => 5000,  // after 5000 msec, message will be retried
    "auto_finish" => true,
);

**Comment by yunnian** [comment]
中国的兄弟我直接中文了

topic 和 channel  就不用说了吧，这个就你要监听的，在nsqadmin上你可以创建
rdy 是你一次要收多少条消息
connect_num是启动多少个链接消费，这个你可以在nsqadmin的channel详情看到
retry_delay_time 是你如果想重试这条消息 ，多长时间会再次发送过来让你消费，默认为0，callback没有正常调用，或者收到个异常消息会重试
auto_finish 默认为true ，没有特殊要求不用管，false的话需要你手动 调用message类的finish方法去手动ack

**Comment by icyxp** [comment]
哈哈，感谢，后续用的过程中有问题，及时和你联系！谢谢！

**Comment by yunnian** [comment]
不是一个东西，max in flight是总和

**Comment by icyxp** [comment]
max_in_flight 不是总和吧，你看nsq go client 里的实现。就是最大消息数

**Comment by yunnian** [comment]
rdy是每个链接的数

**Comment by icyxp** [comment]
那设置一个consumer 一次允许消费最大的消息数量 你有实现吗？golang client sdk是通过max_in_flight来设置的，有赞的php sdk 也是这个参数，现在就不知道你对应的是什么？

**Comment by yunnian** [comment]
rdy 和connect_num相乘就是max in flight,这样更清楚，控制力更强 ，因为可以启动多个连接，rdy是每个连接的最大接收消息数，如果你只有一个 那他就和max in flight相等

**Comment by simple635** [comment]
消费失败，如何return？

**Comment by yunnian** [comment]
@simple635  直接return 就行 return相当于ack了 ，看你是怎么失败的 如果callback调用失败 消息会重试 还会推过来

**Comment by lixuancn** [comment]
Pub:
$nsqdAddr = array(
    "127.0.0.1:4150",
    "127.0.0.1:4154"
);

1、这个4150是干啥的。
2、http://kuangjue.com/article/250#nsqadmin  你的博客可以更新了，方法名都变了

感谢！

**Comment by yunnian** [comment]
@lixuancn  4150是nsqd的端口 ，可以加qq群 有问题随时讨论

**Comment by lixuancn** [comment]
你博客写的是nsqd的tcp是4154，http是4155。然后github上4150+ 4154.。 有点迷惑。已加群。

**Comment by Tinywan** [comment]
@lixuancn 
```php
tcp：4151
HTTP：4150

$nsqdAddr = array(
            "127.0.0.1:4150",
            "127.0.0.1:4151"
        );
```
