### ISSUE TITLE
官方examples 无法获取消费消息

### ISSUE THREAD

**Issue by longhtml** [yunnian/php-nsq#50]
php pub.php,，
php deferred_pub.php，
php identify_pub.php 发布消息成功， nsq_to_file 可以消费消息。  

为何php sub.php， php php identify_sub.php无法获取消费消息，执行php代码无任何报错？

> [root@dev15-113 18:54:25 ~/php-nsq/examples]# php -v 
> PHP 7.0.30 (cli) (built: Apr 22 2019 16:15:30) ( NTS )
> Copyright (c) 1997-2017 The PHP Group
> Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
>     with Zend OPcache v7.0.30, Copyright (c) 1999-2017, by Zend Technologies
> 
> [root@dev15-113 18:54:26 ~/php-nsq/examples]# php -m 
> [PHP Modules]
> bcmath
> Core
> ctype
> curl
> date
> dom
> event
> nsq

**Comment by luoxun** [comment]
@longhtml  你看是不是 你 nsq 的 广播地址 是 host？
