### ISSUE TITLE
打出内存溢出呀

### ISSUE THREAD

**Issue by gmars** [yunnian/php-nsq#54]
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 1213486161 bytes) in /data/wwwroot/juheng/framework/common/component/Nsq.php on line 24

**Comment by yunnian** [comment]
看下地址端口对不  ， 官方pub例子中的4151 是需要单独多起一个nsqd的，你没有就删除

**Comment by studyzhanglei** [comment]
同遇到此问题，ini_set('memory_limit', '-1');得到解决，感觉不是个办法呀～

**Comment by yunnian** [comment]
> 同遇到此问题，ini_set('memory_limit', '-1');得到解决，感觉不是个办法呀～

你要注意close 链接

**Comment by studyzhanglei** [comment]
> > 同遇到此问题，ini_set('memory_limit', '-1');得到解决，感觉不是个办法呀～
> 
> 你要注意close 链接

官方demo，下面有close的，消费消息也有点问题

**Comment by littlexiang** [comment]
同样遇到, 一旦port或者地址错误就会吃掉2G内存, 疑似死循环
默认应该使用port 4150(tcp) 而非 4151(http)
