### ISSUE TITLE
deferredPublish 方法可以加一个 返回值吗

### ISSUE THREAD

**Issue by xibusuper** [yunnian/php-nsq#57]
deferredPublish 方法可以加一个 返回值吗？

> $deferred = new Nsq();
   $isTrue = $deferred->connectNsqd($nsqdAddr);
   for($i = 0; $i < 20; $i++){
        $ret = $deferred->deferredPublish("test", "message daly", 3000);
        var_dump($ret);
  }
 $deferred->closeNsqdConnection();

延迟队列写入成功了  但是  打印 $ret    还是为 false     publish("test", "message")   这个方法 返回为 true     

现在是通过这个$ret 返回值  来判断是否把 消息 成功写入队列  如果 deferredPublish 这个的返回值成功或失败都是false   就不确定是否成功写入了队列。 
麻烦了大神！

**Comment by yunnian** [comment]
你好 你用的什么版本，之前老版本有这个问题

**Comment by xibusuper** [comment]
nsq 3.5.0  我是用 pecl install nsq  安装的
![55555](https://user-images.githubusercontent.com/22129256/72656674-f33f8680-39d7-11ea-9638-a7d571c56275.png)

**Comment by yunnian** [comment]
已修复
