### ISSUE TITLE
php7.2.2  调用connect_nsqd 报错

### ISSUE THREAD

**Issue by icyxp** [yunnian/php-nsq#6]
<?php
$nsqd_addr = array(
    "127.0.0.1:4150",
);

$nsq = new Nsq();
$is_true = $nsq->connect_nsqd($nsqd_addr);
for($i = 0; $i < 1; $i++){
    $nsq->publish("INNO-SYS_OCR.UNZIP", "nihao");
}

PHP Fatal error:  Uncaught Error: Call to undefined method Nsq::connect_nsqd()

**Comment by icyxp** [comment]
好吧，你readme里写错了，用connectNsqd 这个才行 - -！

**Comment by yunnian** [comment]
收到 谢谢提醒
