### ISSUE TITLE
pub 不支持域名+端口

### ISSUE THREAD

**Issue by icyxp** [yunnian/php-nsq#7]
`[root@b2c5889d14dc miscroservice]# php 2.php    
connect() error
bool(true)
^C
[root@b2c5889d14dc miscroservice]# cat 2.php 
<?php
$nsqd_addr = array(
    "nsq.innosnap.local:4150"
);

$nsq = new Nsq();
$is_true = $nsq->connectNsqd($nsqd_addr);
var_dump($is_true);
$nsq->publish("INNO-SYS_OCR.UNZIP", "nihao");

[root@b2c5889d14dc miscroservice]# php 2.php 
bool(true)
[root@b2c5889d14dc miscroservice]# cat 2.php 
<?php
$nsqd_addr = array(
    "192.168.3.74:4150"
);

$nsq = new Nsq();
$is_true = $nsq->connectNsqd($nsqd_addr);
var_dump($is_true);
$nsq->publish("INNO-SYS_OCR.UNZIP", "nihao");

[root@b2c5889d14dc miscroservice]# telnet nsq.innosnap.local 4150
Trying 192.168.3.74...
Connected to nsq.innosnap.local.
Escape character is '^]'.`

**Comment by yunnian** [comment]
收到 ，两天后完成 ，这两天过年家里有点忙 请见谅

**Comment by icyxp** [comment]
好的，万分感谢！

**Comment by yunnian** [comment]
已经完成了，你拉最新master代码试下  ，忙了一天，凌晨三点把这个做了 0.0

**Comment by icyxp** [comment]
感谢，幸苦了！
